# Removed the version field as it's no longer needed in newer Docker Compose versions
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/backend
    environment:
      - FLASK_ENV=development  # Adjust as necessary

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080  # The URL for your backend API